import '/core/helpers/app_enums.dart';
import '/features/home/domain/entities/task.dart';

final DateTime timeNow = DateTime.now();
final List<Task> enTasks = [
  Task(
    id: "1",
    title: "Buy groceries for the whole week",
    note: "Milk, Bread, Eggs, Fruits, Vegetables, and some snacks for work.",
    done: false,
    priority: TaskPriority.medium,
    time: timeNow,
  ),
  Task(
    id: "2",
    title: "Read Flutter documentation",
    note: "Focus on localization, storage, and navigation animations sections.",
    done: true,
    priority: TaskPriority.high,
    time: timeNow,
  ),
  Task(
    id: "3",
    title: "Call Ahmed",
    note: "Discuss project deadlines and the upcoming client meeting.",
    done: false,
    priority: TaskPriority.low,
    time: timeNow,
  ),
  Task(
    id: "4",
    title: "Finish UI design for the home screen",
    note: "Ensure responsive layout and consistent color palette.",
    done: true,
    priority: TaskPriority.high,
    time: timeNow,
  ),
  Task(
    id: "5",
    title: "Walk the dog",
    note: "Evening walk around the park.",
    done: false,
    priority: TaskPriority.low,
    time: timeNow,
  ),
  Task(
    id: "6",
    title: "Study Spanish",
    note: "Focus on numbers, alphabet, and common travel phrases.",
    done: false,
    priority: TaskPriority.medium,
    time: timeNow,
  ),
  Task(
    id: "7",
    title: "Backup laptop files",
    note: "Transfer documents and photos to external drive and Google Drive.",
    done: true,
    priority: TaskPriority.medium,
    time: timeNow,
  ),
  Task(
    id: "8",
    title: "Workout",
    note: "30 minutes cardio and 15 minutes stretching.",
    done: false,
    priority: TaskPriority.low,
    time: timeNow,
  ),
  Task(
    id: "9",
    title: "Write a blog post about productivity habits",
    note:
        "Include morning routines, focus techniques, and examples of small daily improvements.",
    done: false,
    priority: TaskPriority.high,
    time: timeNow,
  ),
  Task(
    id: "10",
    title: "Reply to important emails",
    note: "Check inbox for unread client messages and respond before noon.",
    done: true,
    priority: TaskPriority.medium,
    time: timeNow,
  ),
];
final List<Task> arTasks = [
  Task(
    id: "1",
    title: "شراء مستلزمات الأسبوع",
    note: "حليب، خبز، بيض، فواكه، خضروات، وبعض الوجبات الخفيفة للعمل.",
    done: false,
    priority: TaskPriority.medium,
    time: timeNow,
  ),
  Task(
    id: "2",
    title: "قراءة توثيق فلاتر",
    note: "التركيز على أقسام الترجمة، التخزين، وحركات التنقل.",
    done: true,
    priority: TaskPriority.high,
    time: timeNow,
  ),
  Task(
    id: "3",
    title: "الاتصال بأحمد",
    note: "لمناقشة مواعيد تسليم المشروع والاجتماع القادم مع العميل.",
    done: false,
    priority: TaskPriority.low,
    time: timeNow,
  ),
  Task(
    id: "4",
    title: "إنهاء تصميم واجهة المستخدم للصفحة الرئيسية",
    note: "التأكد من أن التصميم متجاوب وأن الألوان متناسقة في كل الصفحات.",
    done: true,
    priority: TaskPriority.high,
    time: timeNow,
  ),
  Task(
    id: "5",
    title: "تمشية الكلب",
    note: "نزهة مسائية قصيرة في الحديقة القريبة.",
    done: false,
    priority: TaskPriority.low,
    time: timeNow,
  ),
  Task(
    id: "6",
    title: "دراسة اللغة الإسبانية",
    note: "التركيز على الأرقام، الحروف، وبعض الجمل المستخدمة في السفر.",
    done: false,
    priority: TaskPriority.medium,
    time: timeNow,
  ),
  Task(
    id: "7",
    title: "أخذ نسخة احتياطية من ملفات اللابتوب",
    note: "نقل المستندات والصور إلى القرص الخارجي وGoogle Drive.",
    done: true,
    priority: TaskPriority.medium,
    time: timeNow,
  ),
  Task(
    id: "8",
    title: "ممارسة التمارين الرياضية",
    note: "30 دقيقة كارديو و15 دقيقة تمارين إطالة.",
    done: false,
    priority: TaskPriority.low,
    time: timeNow,
  ),
  Task(
    id: "9",
    title: "كتابة مقال عن عادات الإنتاجية",
    note:
        "تضمين روتين الصباح، طرق زيادة التركيز، وأمثلة على تحسينات بسيطة يومية.",
    done: false,
    priority: TaskPriority.high,
    time: timeNow,
  ),
  Task(
    id: "10",
    title: "الرد على الرسائل الإلكترونية المهمة",
    note: "مراجعة البريد والرد على رسائل العملاء قبل الظهر.",
    done: true,
    priority: TaskPriority.medium,
    time: timeNow,
  ),
];
